// Generated by CoffeeScript 1.3.1
(function() {
  var Gurl;

  Gurl = (function() {

    Gurl.name = 'Gurl';

    function Gurl() {
      this.targetBlankNonSelfRefURLS = true;
    }

    Gurl.prototype.load = function(glog) {
      var _this = this;
      return glog.registerPostArticleHook(function(articles, cb) {
        return cb(_this.processArticles(articles));
      });
    };

    Gurl.prototype.processArticles = function(articles) {
      return console.log(articles);
    };

    return Gurl;

  })();

  module.exports = new Gurl();

}).call(this);
